remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme

defaults:
  - scope:
      path: "obojima/PRIVATE" # This should cover the folder
    values:
      layout: "private"
  - scope:
      path: "obojima/PRIVATE/ness" # Explicitly add sub-folders if they are being stubborn
    values:
      layout: "private"