remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme

defaults:
  - scope:
      path: "obojima/PRIVATE"
    values:
      layout: "private"
  - scope:
      path: "obojima/PRIVATE/ness"
    values:
      layout: "private"